version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: tsed-unique-example/server:latest
    ports:
      - '8081:8081'
    stdin_open: true
    tty: true
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
